# Project
site_name: GL Data Workshops
site_description: Workshop on Effective Cluster Usage and Data Management
site_author: Shreyas Gadgin Matha

# Repository
repo_name: cid-harvard/workshop-cluster-training
repo_url: https://github.com/cid-harvard/workshop-cluster-training
edit_uri: ""

# Add license info
copyright: >
    Licensed under the <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution License</a> unless otherwise noted. –
    <a href="#__consent">Change cookie settings</a>

# Theme
theme:
    name: material
    language: en
    palette:
        # Palette toggle for light mode
        - scheme: default
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-7 
              name: Switch to dark mode

        # Palette toggle for dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
        
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    
    features:
        - content.code.annotate
        - content.tooltips
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
        - toc.integrate

# Customization
extra_css:
    - 'stylesheets/extra.css'
# Social
extra:
    analytics:
        provider: google
        property: UA-76189439-3
    consent:
        title: Cookie consent
        description: >- 
            We use cookies for analytics to track user visits to different pages, to track the effectiveness of our documentation.
        cookies:
            analytics: Analytics
        actions:
            - accept
            - manage
    social:
        - icon: fontawesome/brands/github-alt
          link: https://github.com/shreyasgm
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/shreyasgm
        - icon: fontawesome/brands/linkedin
          link: https://linkedin.com/in/shreyasgm/

# Markdown extensions
markdown_extensions:
    - admonition
    - footnotes
    - codehilite:
        linenums: true
    - toc:
        permalink: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.superfences
    - pymdownx.details

# Navigation structure
nav:
    - Home: index.md
    - Data Management:
        - Overview: data_management/data_management.md
        - Folder structures: data_management/folder_structure.md
    - FASRC Cluster Training:
        - Basic usage: cluster_usage/fasrc_basic_cluster_usage.md
        - Advanced usage: cluster_usage/fasrc_advanced_cluster_usage.md
        - Running Python Remotely: cluster_usage/fasrc_remote_python.md
    - RCE Cluster Training:
        - Basic Commands: cluster_usage/rce_basic_cluster_usage.md
        - Running Python Remotely: cluster_usage/rce_remote_python_options.md
        - Running Stata Remotely: cluster_usage/rce_remote_stata_options.md
