# Project
site_name: CID Data Workshops
site_description: Workshop on Effective Cluster Usage and Data Management
site_author: Shreyas Gadgin Matha

# Repository
repo_name: cid-harvard/workshop-cluster-training
repo_url: https://github.com/cid-harvard/workshop-cluster-training
edit_uri: ""

# Theme
theme:
    name: material
    language: en
    feature:
        tabs: false
    palette:
        primary: indigo
        accent: indigo
    font:
        text: 'Roboto'
        code: 'Roboto Mono'

# Customization
extra_css:
    - 'stylesheets/extra.css'
# Social
extra:
    social:
        - type: github-alt
          link: https://github.com/shreyasgm
        - type: twitter
          link: https://twitter.com/shreyasgm
        - type: linkedin
          link: https://linkedin.com/in/shreyasgm/

# Markdown extensions
markdown_extensions:
    - admonition
    - footnotes
    - codehilite:
        linenums: true
    - toc:
        permalink: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.superfences

# Google analytics
google_analytics:
    - 'UA-76189439-3'
    - 'auto'

# Navigation structure
nav:
    - Home: index.md
    - Data Management:
        - Overview: data_management/data_management.md
        - Folder structures: data_management/folder_structure.md
    - Cluster Training:
        - Basic Commands: cluster_usage/basic_cluster_usage.md
        - Running Stata Remotely: cluster_usage/remote_stata_options.md
