# Project
site_name: CID Data Workshops
site_description: Workshop on Effective Cluster Usage and Data Management
site_author: Shreyas Gadgin Matha

# Repository
repo_name: cid-harvard/workshop-cluster-training
repo_url: https://github.com/cid-harvard/workshop-cluster-training
edit_uri: ""

# Add license info
copyright: 'Licensed under the <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution License</a> unless otherwise noted.'

# Theme
theme:
    name: material
    language: en
    palette:
        primary: indigo
        accent: indigo
    font:
        text: 'Roboto'
        code: 'Roboto Mono'

# Customization
extra_css:
    - 'stylesheets/extra.css'
# Social
extra:
    social:
        - icon: fontawesome/brands/github-alt
          link: https://github.com/shreyasgm
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/shreyasgm
        - icon: fontawesome/brands/linkedin
          link: https://linkedin.com/in/shreyasgm/

# Markdown extensions
markdown_extensions:
    - admonition
    - footnotes
    - codehilite:
        linenums: true
    - toc:
        permalink: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.superfences
    - pymdownx.details

# Google analytics
google_analytics:
    - 'UA-76189439-3'
    - 'auto'

# Navigation structure
nav:
    - Home: index.md
    - Data Management:
        - Overview: data_management/data_management.md
        - Folder structures: data_management/folder_structure.md
    - FASRC Cluster Training:
        - Basic Usage and Commands: cluster_usage/fasrc_basic_cluster_usage.md
        - Running Python Remotely: cluster_usage/fasrc_remote_python.md
    - RCE Cluster Training:
        - Basic Commands: cluster_usage/basic_cluster_usage.md
        - Running Python Remotely: cluster_usage/remote_python_options.md
        - Running Stata Remotely: cluster_usage/remote_stata_options.md
